services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - MYSQL_ACTIVE=True
      - DB_HOST=db
      - DB_NAME=ecommerce
      - DB_PASSWORD=test1234
      - DB_USER=root
      - DB_PORT=3306
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: mysql
    container_name: ecommerce-mysql
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A ecommerce worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A ecommerce beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

volumes:
  db_data:
